version: "3.8"
services:
  bbdate-front:
    container_name: "bbdate-front"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/bbdate-front
    working_dir: /bbdate-front
    command: sh -c "yarn start"
    ports:
      - 8080:8080
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
